### ISSUE TITLE
Apollo Client 3 documentation

### ISSUE THREAD

**Issue by hwillson** [apollographql/apollo-feature-requests#218]
As we get closer to an AC3 RC, we need to make sure the docs are properly updated to accommodate all of AC3's changes. While we've started a lot of this work already (https://www.apollographql.com/docs/react/v3.0-beta) there is much more to do. We'll use this issue to track that outstanding work.

**TODO:**

- [ ] Reactive variables / `cache.makeVar`
- [ ] Deprecate local resolvers
- [ ] `cache.modify` / `cache.delete`
- [ ] Show how to handle cache redirects with cache policies
- [ ] Remove `cacheRedirects`
- [ ] Remove `writeData`
- [ ] More examples using cache policies with root queries (typename `Query`)
- [ ] Migration guide updates

**Comment by raarts** [comment]
Docs should clarify on why it recommends certain things. For example, the subscription section states:

> Apollo Client should use your WebSocketLink for subscriptions, but it _shouldn't_ use it for queries or mutations. For those operations, Apollo Client should use HTTP as usual

why is this? Or another one:

_In the majority of cases, your client should not use subscriptions to stay up to date with your backend. Instead, you should poll intermittently with queries, or re-execute queries on demand when a user performs a relevant action._

What is the downside if I do anyway? More clarification is needed. Personally I would like to use subscriptions instead of queries on every screen.

**Comment by jpvajda** [comment]
Since AC 3 has been released, I'm closing this out.
